### PR TITLE
Issue-103 Incompatible with new SonarJava 5.8 plugin (on SonarQube 7.3)

### LINKED ISSUE #103: Incompatible with new SonarJava 5.8 plugin (on SonarQube 7.3)
When installed along with SonarJava 5.8 (Build 15699), Sonar analysis fails. I am getting this error during analysis:

15:18:31 [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project com.###.###.###: SonarQube is unable to analyze file : '/###/###/###.java': java.lang.reflect.InvocationTargetException: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object; -> [Help 1]

I am getting the very same error for each Java project that is analysed using SonarQube 7.3 / SonarJava 5.8 / AEM Rules for SonarQube 0.10 (and a snapshot build of 0.11 source from 10/19/2018)

Rolling back the SonarJava plugin to a previous release (5.7) fixes the issue (tested with a snapshot build of aEM Rules for SonarQube 0.11 of 10/19/2018).

### PR DESCRIPTION
**Pull request by michaltobiasz**
fixes #103

### CODE REVIEW

File: src/main/java/com/cognifide/aemrules/matcher/TypePredicate.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+ */
+package com.cognifide.aemrules.matcher;
+
+import java.util.function.Predicate;
+import org.sonar.plugins.java.api.semantic.Type;
+
+@FunctionalInterface
+public interface TypePredicate extends Predicate<Type> {
+
+    String ANY_TYPE = "ANY_TYPE";
```
Comment (michaltobiasz) [inline src/main/java/com/cognifide/aemrules/matcher/TypePredicate.java]: Do not use constant in interface

File: src/main/java/com/cognifide/aemrules/matcher/MethodMatcher.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+package com.cognifide.aemrules.matcher;
+
+import org.sonar.plugins.java.api.semantic.Symbol;
+import org.sonar.plugins.java.api.semantic.Symbol.MethodSymbol;
+import org.sonar.plugins.java.api.tree.IdentifierTree;
+import org.sonar.plugins.java.api.tree.MemberSelectExpressionTree;
+import org.sonar.plugins.java.api.tree.MethodInvocationTree;
+import org.sonar.plugins.java.api.tree.Tree;
+
+public final class MethodMatcher {
```
Comment (michaltobiasz) [inline src/main/java/com/cognifide/aemrules/matcher/MethodMatcher.java]: Add unit tests

File: pom.xml [hunk 3]
```diff
@@ -106,6 +107,11 @@
       <artifactId>guava</artifactId>
       <version>19.0</version>
     </dependency>
+    <dependency>
+      <groupId>commons-lang</groupId>
+      <artifactId>commons-lang</artifactId>
```
Comment (toniedzwiedz) [inline pom.xml]: Why not use `commons-lang3` instead?

Comment (toniedzwiedz) [inline pom.xml]: Why not use `commons-lang3` instead?
Also, unless I'm misreading the changes Github is displaying here, this newly introduced dependency is not actually used.

Comment (michaltobiasz) [reply pom.xml]: The non-obvious reason is that previously we where using class loader of base plugin and commons-lang was available. We have some classes which use this lib (not changed/added in this commit) like RulesLoader or HttpConstantCheck.

Comment (chutch) [reply pom.xml]: Yepp, agree. This is basically carry-over, but since we have full control now, maybe upgrade of this library is worth exploring.

Comment (michaltobiasz) [reply pom.xml]: Question is do we want to do this in this issue?

Comment (chutch) [reply pom.xml]: If you change it and then feel comfortable with that, why not. Hopefully, it will only change imports.

File: src/main/java/com/cognifide/aemrules/checks/AdministrativeAccessUsageCheck.java [hunk 4]
```diff
@@ -57,31 +60,40 @@
         .put("getAdministrativeResourceResolver", "getServiceResourceResolver")
         .build();
 
+    private static final List<MethodMatcher> matchers = ImmutableList.of(
+        MethodMatcher.create(
+            MethodNamePredicate.is("loginAdministrative"),
+            TypePredicate.is("org.apache.sling.jcr.api.SlingRepository"),
```
Comment (chutch) [inline src/main/java/com/cognifide/aemrules/checks/AdministrativeAccessUsageCheck.java]: Well, I think that for readability purpose, it would be great if we can differentiate `OwnerType` and `ParameterType` as it's not really visible her what's happening.

File: src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java [hunk 5]
```diff
@@ -0,0 +1,159 @@
...
+    private static final int CLASS_INDEX = 2;
+
+    private static final int CLASS_METHOD_INDEX = 1;
+
+    private static final int METHOD_INVOCATION_INDEX = 2;
+
+    private MethodInvocationTree methodInvocationTree;
+
+    @Test
+    public void shouldMatchMethodWhenMethodNameOwnerClassAndMethodParametersAgree() {
```
Comment (chutch) [inline src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java]:
```suggestion
    public void shouldMatchMethodWhenMethodNameAndOwnerClassAndMethodParametersMatch() {
```

File: src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java [hunk 6]
```diff
@@ -0,0 +1,159 @@
...
+            TypePredicate.is("com.cognifide.test.TestClass"),
+            TypePredicate.is("com.cognifide.test.MyClass1"),
+            TypePredicate.is("com.cognifide.test.MyClass2")
+        );
+
+        Assert.assertThat(methodMatcher.matches(methodInvocationTree), is(true));
+    }
+
+    @Test
+    public void shouldMatchMethodWhenMethodNameOwnerClassAndOneParameterAnyAndSecondStrict() {
```
Comment (chutch) [inline src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java]:
```suggestion
    public void shouldMatchMethodWhenMethodNameAndOwnerClassAndOnlySecondParameterMatch() {
```

File: src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java [hunk 7]
```diff
@@ -0,0 +1,159 @@
...
+            TypePredicate.is("com.cognifide.test.TestClass"),
+            TypePredicate.anyType(),
+            TypePredicate.is("com.cognifide.test.MyClass2")
+        );
+
+        Assert.assertThat(methodMatcher.matches(methodInvocationTree), is(true));
+    }
+
+    @Test
+    public void shouldNotMatchMethodWhenMethodNameDifferent() {
```
Comment (chutch) [inline src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java]:
```suggestion
    public void shouldNotMatchMethodWhenMethodNameDoesNotMatch() {
```

File: src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java [hunk 8]
```diff
@@ -0,0 +1,159 @@
...
+            TypePredicate.is("com.cognifide.test.TestClass"),
+            TypePredicate.is("com.cognifide.test.MyClass1"),
+            TypePredicate.is("com.cognifide.test.MyClass2")
+        );
+
+        Assert.assertThat(methodMatcher.matches(methodInvocationTree), is(false));
+    }
+
+    @Test
+    public void shouldNotMatchMethodWhenNumberOfMethodParametersDifferent() {
```
Comment (chutch) [inline src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java]:
```suggestion
    public void shouldNotMatchMethodWhenNumberOfMethodParametersDoesNotMatch() {
```

File: src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java [hunk 9]
```diff
@@ -0,0 +1,159 @@
...
+            MethodNamePredicate.is("test"),
+            TypePredicate.is("com.cognifide.test.TestClass"),
+            TypePredicate.is("com.cognifide.test.MyClass1")
+        );
+
+        Assert.assertThat(methodMatcher.matches(methodInvocationTree), is(false));
+    }
+
+    @Test
+    public void shouldNotMatchMethodWhenMethodOwnerClassDifferent() {
```
Comment (chutch) [inline src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java]:
```suggestion
    public void shouldNotMatchMethodWhenMethodOwnerClassDoesNotMatch() {
```

File: src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java [hunk 10]
```diff
@@ -0,0 +1,159 @@
...
+            TypePredicate.is("com.cognifide.test.Different"),
+            TypePredicate.is("com.cognifide.test.MyClass1"),
+            TypePredicate.is("com.cognifide.test.MyClass2")
+        );
+
+        Assert.assertThat(methodMatcher.matches(methodInvocationTree), is(false));
+    }
+
+    @Test
+    public void shouldNotMatchMethodWhenMethodParametersDifferent() {
```
Comment (chutch) [inline src/test/java/com/cognifide/aemrules/matcher/MethodMatcherTest.java]:
```suggestion
    public void shouldNotMatchMethodWhenMethodParameterTypesDoNotMatch() {
```
