### PR TITLE
Issue-109 Use HTL comments FIX for multiline comments and exceptions.

### LINKED ISSUE #109: Use HTL comments
If you want to place comments regarding your code, make sure they don't display to end users.
```
<!--/* Good, this comment will not be rendered */-->
 
<!-- Potentially bad, plain HTML comments will be visible on the page -->
```

### PR DESCRIPTION
**Pull request by GulderBone**
Fixes #109 and a bug from #150.

### CODE REVIEW

File: src/main/java/com/cognifide/aemrules/htl/checks/DisplayContextInConditionalCommentsCheck.java [hunk 1]
```diff
@@ -61,6 +60,10 @@ public void comment(CommentNode node) {
     }
 
     private boolean isConditionalComment(String code) {
-        return CONDITIONAL_COMMENT_PATTERN.matcher(code).matches();
+        return CONDITIONAL_COMMENT_PATTERN.matcher(removeWhitespace(code)).matches();
+    }
+
+    private String removeWhitespace(String code) {
+        return code.replaceAll("\\s+", "");
```
Comment (jplucinski) [inline src/main/java/com/cognifide/aemrules/htl/checks/DisplayContextInConditionalCommentsCheck.java]: Consider using: `StringUtils.deleteWhitespace`.

File: src/main/java/com/cognifide/aemrules/htl/checks/HtlCommentsCheck.java [hunk 2]
```diff
@@ -47,17 +47,32 @@
...
   private static final Pattern CONDITIONAL_COMMENT_PATTERN = Pattern
-      .compile("<!--\\[if.*!\\[endif\\]-->");
+      .compile("<!--\\[.*]-->");
+
+  private static final Pattern ESI_COMMENT_PATTERN = Pattern
+      .compile("<!--esi.*-->");
 
   @Override
   public void comment(CommentNode node) {
     String code = node.getCode();
```
Comment (jplucinski) [inline src/main/java/com/cognifide/aemrules/htl/checks/HtlCommentsCheck.java]: Maybe delete whitespaces chars here.

File: src/main/java/com/cognifide/aemrules/htl/checks/HtlCommentsCheck.java [hunk 3]
```diff
@@ -47,17 +47,32 @@
...
-    if (!Syntax.isSightlyComment(code) && !isConditionalComment(code)) {
+    if (!Syntax.isSightlyComment(code) && !isException(code)) {
       createViolation(node.getStartLinePosition(), RULE_MESSAGE);
     }
   }
 
+  private boolean isException(String code) {
+    return isConditionalComment(code) || isESIComment(code);
```
Comment (jplucinski) [inline src/main/java/com/cognifide/aemrules/htl/checks/HtlCommentsCheck.java]: I would rather create static list of patterns 'exceptions' 

`EXCEPTIONS = Lists.newArrayList(CONDITIONAL_COMMENT_PATTERN, ESI_COMMENT_PATTERN)`

the use:

```
exceptions.stream()
.map(pattern -> pattern.matcher(code))
.anyMatch(Matcher::matches);
```

It would be easier to add more regex patterns.

File: src/test/files/checks/htl/HtlCommentsCheck.html [hunk 4]
```diff
@@ -1,5 +1,17 @@
-<!--/* Good, this comment will not be rendered */-->
```
Comment (jplucinski) [inline src/test/files/checks/htl/HtlCommentsCheck.html]: What about supporting Apache SSI?
http://httpd.apache.org/docs/current/mod/mod_include.html

File: src/main/java/com/cognifide/aemrules/htl/checks/HtlCommentsCheck.java (hunk 2 above)
Comment (GulderBone) [reply src/main/java/com/cognifide/aemrules/htl/checks/HtlCommentsCheck.java]: Done

File: src/main/java/com/cognifide/aemrules/htl/checks/DisplayContextInConditionalCommentsCheck.java (hunk 1 above)
Comment (GulderBone) [reply src/main/java/com/cognifide/aemrules/htl/checks/DisplayContextInConditionalCommentsCheck.java]: Done, thanks.

File: src/main/java/com/cognifide/aemrules/htl/checks/HtlCommentsCheck.java (hunk 3 above)
Comment (GulderBone) [reply src/main/java/com/cognifide/aemrules/htl/checks/HtlCommentsCheck.java]: Done, looks nice.

File: src/test/files/checks/htl/HtlCommentsCheck.html (hunk 4 above)
Comment (GulderBone) [reply src/test/files/checks/htl/HtlCommentsCheck.html]: Please take a low now: https://github.com/Cognifide/AEM-Rules-for-SonarQube/pull/166/commits/932e208985e313b589307d9eff36f01e2771220c
